// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using customerService;

namespace customerService.Migrations
{
    [DbContext(typeof(DBContext))]
    [Migration("20190709083051_second")]
    partial class second
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.11-servicing-32099")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("customerService.Models.Order", b =>
                {
                    b.Property<int>("SerialNo")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Order_Idd");

                    b.Property<string>("Order_Status");

                    b.Property<int>("Total_Items");

                    b.Property<float>("Total_Price");

                    b.Property<float>("Total_Sum_Tax");

                    b.Property<float>("Total_Tax");

                    b.HasKey("SerialNo");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("customerService.Models.Order_Products", b =>
                {
                    b.Property<int>("SerialNo")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("Order_Id");

                    b.Property<int?>("Product_Id");

                    b.HasKey("SerialNo");

                    b.HasIndex("Order_Id");

                    b.HasIndex("Product_Id");

                    b.ToTable("Orders_Products");
                });

            modelBuilder.Entity("customerService.Models.Product", b =>
                {
                    b.Property<int>("Product_Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Product_Des");

                    b.Property<string>("Product_Name");

                    b.Property<float>("Product_Price");

                    b.Property<float>("Product_Tax");

                    b.HasKey("Product_Id");

                    b.ToTable("Products");

                    b.HasData(
                        new { Product_Id = 1, Product_Des = "white sause", Product_Name = "Pasta", Product_Price = 880f, Product_Tax = 50f },
                        new { Product_Id = 2, Product_Des = "grilled", Product_Name = "Chicken", Product_Price = 880f, Product_Tax = 50f },
                        new { Product_Id = 3, Product_Des = "labaniese sause", Product_Name = "Burger", Product_Price = 880f, Product_Tax = 50f },
                        new { Product_Id = 4, Product_Des = "chicken maushroom sause", Product_Name = "stake", Product_Price = 880f, Product_Tax = 50f },
                        new { Product_Id = 5, Product_Des = "BBQ", Product_Name = "pizza", Product_Price = 880f, Product_Tax = 50f }
                    );
                });

            modelBuilder.Entity("customerService.Models.Order_Products", b =>
                {
                    b.HasOne("customerService.Models.Order", "Order_ref")
                        .WithMany()
                        .HasForeignKey("Order_Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("customerService.Models.Product", "Product_ref")
                        .WithMany()
                        .HasForeignKey("Product_Id");
                });
#pragma warning restore 612, 618
        }
    }
}
